apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: easy-circulars-backend-deployment
  name: easy-circulars-backend-deployment
  namespace: easy-circulars
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: easy-circulars-backend-deployment
  template:
    metadata:
      annotations:
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: easy-circulars-backend-deployment
    spec:
      containers:
        - env:
            - name: EMBEDDING_SERVER_HOST_IP
              value: easy-circulars-embedding-service-deployment
            - name: EMBEDDING_SERVER_PORT
              value: "80"
            - name: HTTPS_PROXY
              value: http://proxy-dmz.intel.com:912
            - name: HTTP_PROXY
              value: http://proxy-dmz.intel.com:912
            - name: LLM_MODEL
              value: meta-llama/Meta-Llama-3.1-8B-Instruct
            - name: LLM_SERVER_HOST_IP
              value: easy-circulars-groq-deployment
            - name: LLM_SERVER_PORT
              value: "8000"
            - name: LOGFLAG
              value: "true"
            - name: MEGA_SERVICE_HOST_IP
              value: 127.0.0.1
            - name: MEGA_SERVICE_PORT
              value: "5008"
            - name: MONGO_HOST
              value: easy-circulars-mongodb-deployment
            - name: RERANK_SERVER_HOST_IP
              value: easy-circulars-tei-reranking-deployment
            - name: RERANK_SERVER_PORT
              value: "80"
            - name: RETRIEVER_SERVICE_HOST_IP
              value: easy-circulars-retriever-deployment
            - name: RETRIEVER_SERVICE_PORT
              value: "7000"
            - name: http_proxy
              value: http://proxy-dmz.intel.com:912
            - name: https_proxy
              value: http://proxy-dmz.intel.com:912
            - name: no_proxy
              value: 127.0.0.1,localhost,.intel.com,10.235.124.11,10.235.124.12,10.235.124.13,10.96.0.0/12,10.235.64.0/18,easy-circulars-ui,easy-circulars-backend,easy-circulars-dataprep,easy-circulars-retriever,easy-circulars-tei-reranking,easy-circulars-embedding-service,easy-circulars-mongodb,easy-circulars-groq,easy-circulars-redis,192.168.49.2
          image: tanmayudupa124/easy-circulars-backend:latest
          imagePullPolicy: Always
          name: easy-circulars-backend-container
          ports:
            - containerPort: 5008
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: easy-circulars-backend-deployment
  name: easy-circulars-backend-deployment
  namespace: easy-circulars
spec:
  type: NodePort
  ports:
    - name: "5013"
      port: 5013
      protocol: TCP
      targetPort: 5008
      nodePort: 30001
  selector:
    io.kompose.service: easy-circulars-backend-deployment