apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: easy-circulars-dataprep-deployment
  name: easy-circulars-dataprep-deployment
  namespace: easy-circulars
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: easy-circulars-dataprep-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: easy-circulars-dataprep-deployment
    spec:
      containers:
        - env:
            - name: HTTPS_PROXY
              value: http://proxy-dmz.intel.com:912
            - name: HTTP_PROXY
              value: http://proxy-dmz.intel.com:912
            - name: HUGGINGFACEHUB_API_TOKEN
              value: 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
            - name: LLM_SERVER_HOST_IP
              value: easy-circulars-groq-deployment
            - name: LLM_SERVER_PORT
              value: "8000"
            - name: LOGFLAG
              value: "true"
            - name: REDIS_URL
              value: redis://easy-circulars-redis:6379
            - name: TEI_EMBEDDING_ENDPOINT
              value: http://easy-circulars-embedding-service:80
            - name: http_proxy
              value: http://proxy-dmz.intel.com:912
            - name: https_proxy
              value: http://proxy-dmz.intel.com:912
            - name: no_proxy
              value: 127.0.0.1,localhost,.intel.com,10.235.124.11,10.235.124.12,10.235.124.13,10.96.0.0/12,10.235.64.0/18,easy-circulars-ui,easy-circulars-backend,easy-circulars-dataprep,easy-circulars-retriever,easy-circulars-tei-reranking,easy-circulars-embedding-service,easy-circulars-mongodb,easy-circulars-groq,easy-circulars-redis,192.168.49.2
          image: tanmayudupa124/easy-circulars-dataprep:latest
          name: easy-circulars-dataprep-container
          ports:
            - containerPort: 6007
              protocol: TCP
          volumeMounts:
            - mountPath: /.cache
              name: easy-circulars-dataprep-claim0
            - mountPath: /home/user/comps/dataprep/out
              name: easy-circulars-dataprep-claim1
      restartPolicy: Always
      volumes:
        - name: easy-circulars-dataprep-claim0
          persistentVolumeClaim:
            claimName: easy-circulars-dataprep-claim0
        - name: easy-circulars-dataprep-claim1
          persistentVolumeClaim:
            claimName: easy-circulars-dataprep-claim1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: easy-circulars-dataprep-deployment
  name: easy-circulars-dataprep-deployment
  namespace: easy-circulars
spec:
  type: NodePort
  ports:
    - name: "5012"
      port: 5012
      protocol: TCP
      targetPort: 6007
      nodePort: 30002
  selector:
    io.kompose.service: easy-circulars-dataprep-deployment
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: easy-circulars-dataprep-claim0
  name: easy-circulars-dataprep-claim0
  namespace: easy-circulars
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: easy-circulars-dataprep-claim1
  name: easy-circulars-dataprep-claim1
  namespace: easy-circulars
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi