apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: easy-circulars-embedding-service-deployment
  name: easy-circulars-embedding-service-deployment
  namespace: easy-circulars
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: easy-circulars-embedding-service-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: easy-circulars-embedding-service-deployment
    spec:
      containers:
        - args:
            - --model-id
            - BAAI/bge-base-en-v1.5
            - --auto-truncate
          env:
            - name: HTTPS_PROXY
              value: http://proxy-dmz.intel.com:912
            - name: HTTP_PROXY
              value: http://proxy-dmz.intel.com:912
            - name: http_proxy
              value: http://proxy-dmz.intel.com:912
            - name: https_proxy
              value: http://proxy-dmz.intel.com:912
            - name: no_proxy
              value: 127.0.0.1,localhost,.intel.com,10.235.124.11,10.235.124.12,10.235.124.13,10.96.0.0/12,10.235.64.0/18,easy-circulars-ui,easy-circulars-backend,easy-circulars-dataprep,easy-circulars-retriever,easy-circulars-tei-reranking,easy-circulars-embedding-service,easy-circulars-mongodb,easy-circulars-groq,easy-circulars-redis,192.168.49.2
          image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
          name: easy-circulars-embedding-service-container
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: easy-circulars-embedding-service-claim0
      restartPolicy: Always
      volumes:
        - name: easy-circulars-embedding-service-claim0
          persistentVolumeClaim:
            claimName: easy-circulars-embedding-service-claim0
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: easy-circulars-embedding-service-deployment
  name: easy-circulars-embedding-service-deployment
  namespace: easy-circulars
spec:
  type: NodePort
  ports:
    - name: "6010"
      port: 6010
      protocol: TCP
      targetPort: 80
      nodePort: 30003
  selector:
    io.kompose.service: easy-circulars-embedding-service-deployment
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: easy-circulars-embedding-service-claim0
  name: easy-circulars-embedding-service-claim0
  namespace: easy-circulars
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi