apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: easy-circulars-groq-deployment
  name: easy-circulars-groq-deployment
  namespace: easy-circulars
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: easy-circulars-groq-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: easy-circulars-groq-deployment
    spec:
      containers:
        - env:
            - name: GROQ_API_KEY
              value: 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
            - name: HTTPS_PROXY
              value: http://proxy-dmz.intel.com:912
            - name: HTTP_PROXY
              value: http://proxy-dmz.intel.com:912
            - name: http_proxy
              value: http://proxy-dmz.intel.com:912
            - name: https_proxy
              value: http://proxy-dmz.intel.com:912
            - name: no_proxy
              value: 127.0.0.1,localhost,.intel.com,10.235.124.11,10.235.124.12,10.235.124.13,10.96.0.0/12,10.235.64.0/18,easy-circulars-ui,easy-circulars-backend,easy-circulars-dataprep,easy-circulars-retriever,easy-circulars-tei-reranking,easy-circulars-embedding-service,easy-circulars-mongodb,easy-circulars-groq,easy-circulars-redis,192.168.49.2
          image: tanmayudupa124/easy-circulars-groq:latest
          name: easy-circulars-groq-container
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /root/.cache
              name: easy-circulars-groq-claim0
      restartPolicy: Always
      volumes:
        - name: easy-circulars-groq-claim0
          persistentVolumeClaim:
            claimName: easy-circulars-groq-claim0
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: easy-circulars-groq-deployment
  name: easy-circulars-groq-deployment
  namespace: easy-circulars
spec:
  type: NodePort
  ports:
    - name: "5101"
      port: 5101
      protocol: TCP
      targetPort: 8000
      nodePort: 30004
  selector:
    io.kompose.service: easy-circulars-groq-deployment
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: easy-circulars-groq-claim0
  name: easy-circulars-groq-claim0
  namespace: easy-circulars
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi