apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: easy-circulars-mongodb-deployment
  name: easy-circulars-mongodb-deployment
  namespace: easy-circulars
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: easy-circulars-mongodb-deployment
  template:
    metadata:
      annotations:
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: easy-circulars-mongodb-deployment
    spec:
      containers:
        - image: mongo
          name: easy-circulars-mongodb-container
          ports:
            - containerPort: 27017
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: easy-circulars-mongodb-deployment
  name: easy-circulars-mongodb-deployment
  namespace: easy-circulars
spec:
  type: NodePort
  ports:
    - name: "27018"
      port: 27018
      protocol: TCP
      targetPort: 27017
      nodePort: 30005
  selector:
    io.kompose.service: easy-circulars-mongodb-deployment