apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: easy-circulars-redis-deployment
  name: easy-circulars-redis-deployment
  namespace: easy-circulars
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: easy-circulars-redis-deployment
  template:
    metadata:
      annotations:
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: easy-circulars-redis-deployment
    spec:
      nodeSelector:
        kubernetes.io/hostname: g2-r1-2
      containers:
        - image: redis/redis-stack:7.2.0-v9
          name: easy-circulars-redis-container
          ports:
            - containerPort: 6379
              protocol: TCP
            - containerPort: 8001
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: easy-circulars-redis-deployment
  name: easy-circulars-redis-deployment
  namespace: easy-circulars
spec:
  type: NodePort
  ports:
    - name: "6381"
      port: 6381
      protocol: TCP
      targetPort: 6379
      nodePort: 30006
    - name: "8002"
      port: 8002
      protocol: TCP
      targetPort: 8001
      nodePort: 30016
  selector:
    io.kompose.service: easy-circulars-redis-deployment