apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: easy-circulars-retriever-deployment
  name: easy-circulars-retriever-deployment
  namespace: easy-circulars
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: easy-circulars-retriever-deployment
  template:
    metadata:
      annotations:
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: easy-circulars-retriever-deployment
    spec:
      containers:
        - env:
            - name: HTTPS_PROXY
              value: http://proxy-dmz.intel.com:912
            - name: HTTP_PROXY
              value: http://proxy-dmz.intel.com:912
            - name: HUGGINGFACEHUB_API_TOKEN
              value: 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
            - name: INDEX_NAME
              value: rag-redis
            - name: REDIS_URL
              value: redis://easy-circulars-redis:6379
            - name: TEI_EMBEDDING_ENDPOINT
              value: http://easy-circulars-embedding-service:80
            - name: http_proxy
              value: http://proxy-dmz.intel.com:912
            - name: https_proxy
              value: http://proxy-dmz.intel.com:912
            - name: no_proxy
              value: 127.0.0.1,localhost,.intel.com,10.235.124.11,10.235.124.12,10.235.124.13,10.96.0.0/12,10.235.64.0/18,easy-circulars-ui,easy-circulars-backend,easy-circulars-dataprep,easy-circulars-retriever,easy-circulars-tei-reranking,easy-circulars-embedding-service,easy-circulars-mongodb,easy-circulars-groq,easy-circulars-redis,192.168.49.2
          image: tanmayudupa124/easy-circulars-retriever:latest
          name: easy-circulars-retriever-container
          ports:
            - containerPort: 7000
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: easy-circulars-retriever-deployment
  name: easy-circulars-retriever-deployment
  namespace: easy-circulars
spec:
  type: NodePort
  ports:
    - name: "5011"
      port: 5011
      protocol: TCP
      targetPort: 7000
      nodePort: 30007
  selector:
    io.kompose.service: easy-circulars-retriever-deployment