apiVersion: v1
kind: Namespace
metadata:
  name: easy-circulars
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: easy-circulars-ui-deployment
  name: easy-circulars-ui-deployment
  namespace: easy-circulars
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: easy-circulars-ui-deployment
  template:
    metadata:
      annotations:
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: easy-circulars-ui-deployment
    spec:
      containers:
        - image: tanmayudupa124/easy-circulars-ui:latest
          name: easy-circulars-ui-container
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: easy-circulars-ui-deployment
  name: easy-circulars-ui-deployment
  namespace: easy-circulars
spec:
  type: NodePort
  ports:
    - name: "5014"
      port: 5014
      protocol: TCP
      targetPort: 3000
      nodePort: 30009
  selector:
    io.kompose.service: easy-circulars-ui-deployment